# Generated by Django 3.1.7 on 2021-03-09 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('email', models.CharField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('access', models.CharField(max_length=1, verbose_name='Access level')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eduspace.user')),
                ('eclass', models.CharField(max_length=40, verbose_name='Class')),
            ],
            bases=('eduspace.user',),
        ),
    ]
