# Generated by Django 3.1.7 on 2021-04-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='UNNAMED USER', max_length=30, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='account',
            name='surname',
            field=models.CharField(default='', max_length=30, verbose_name='Surname'),
        ),
    ]
