# Generated by Django 3.1.7 on 2021-03-11 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=-1, verbose_name='Class number')),
                ('letter', models.CharField(max_length=1, verbose_name='Class letter')),
                ('name', models.CharField(max_length=45, verbose_name='Class name')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.CharField(max_length=60, verbose_name='Description')),
                ('information', models.CharField(max_length=150, verbose_name='Information')),
                ('stud_class', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eduspace.class')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.CharField(max_length=60, verbose_name='Description')),
                ('creation_date', models.DateField(verbose_name='Creation date')),
                ('information', models.CharField(max_length=500, verbose_name='Info')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eduspace.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eduspace.user')),
                ('status', models.CharField(default='r', max_length=1, verbose_name='Status')),
            ],
            bases=('eduspace.user',),
        ),
        migrations.RemoveField(
            model_name='student',
            name='eclass',
        ),
        migrations.AddField(
            model_name='user',
            name='name1',
            field=models.CharField(default='name1', max_length=30, verbose_name='Name 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='email', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Name', max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(default='Surname', max_length=30, verbose_name='Surname'),
        ),
        migrations.CreateModel(
            name='PracticeTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eduspace.task')),
                ('deadline', models.DateField(verbose_name='Deadline')),
            ],
            bases=('eduspace.task',),
        ),
        migrations.CreateModel(
            name='TheoryTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eduspace.task')),
            ],
            bases=('eduspace.task',),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eduspace.teacher'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('creation_date', models.DateField(verbose_name='Creation date')),
                ('type', models.CharField(max_length=1, verbose_name='Type')),
                ('class_reciever', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eduspace.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='curator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eduspace.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='stud_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eduspace.class'),
        ),
    ]
