# Generated by Django 3.1.7 on 2021-04-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduspace', '0002_auto_20210411_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=30, verbose_name='Status name')),
                ('abbr', models.CharField(default=None, max_length=3, verbose_name='Abbreviation')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='birthDate',
            field=models.DateField(verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, default='UNNAMED USER', max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eduspace.teacherstatus'),
        ),
    ]
