# Generated by Django 3.1.7 on 2021-03-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduspace', '0002_auto_20210312_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='class_reciever',
            new_name='class_receiver',
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
