# Generated by Django 3.1.7 on 2021-05-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduspace', '0003_auto_20210518_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='class_receiver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eduspace.class'),
        ),
    ]
